version: "3"
services:
  oplogtoredis:
    build:
      context: ..
      dockerfile: blackbox-tests/Dockerfile.oplogtoredis-blackbox
    command:
      - /wait-for.sh
      - redis:7379
      - '--'
      - sh
      - -c
      - |
        update-ca-certificates
        oplogtoredis
    environment:
      - OTR_MONGO_URL=mongodb://cluster0-shard-00-00.uq1yi.mongodb.net:27017,cluster0-shard-00-01.uq1yi.mongodb.net:27017,cluster0-shard-00-02.uq1yi.mongodb.net:27017,cluster0-shard-00-03.uq1yi.mongodb.net:27017,cluster0-shard-00-04.uq1yi.mongodb.net:27017/myFirstDatabase?authMechanism=MONGODB-X509&authSource=%24external&compressors=disabled&gssapiServiceName=mongodb&replicaSet=atlas-epjkn7-shard-0&tls=true&tlsCertificateKeyFile=/mongo-client-certs/testuser.pem
      - OTR_REDIS_URL=rediss://redis:7379
      - OTR_LOG_DEBUG=true
    ports:
      - 9000:9000
    depends_on:
      - redis
    volumes:
      - ./certificates/ca.crt:/usr/local/share/ca-certificates/redis-ca.crt:ro
      - ./mongo-client-certs:/mongo-client-certs:ro
  # mongo:
  #   image: mongo:4.0.5
  #   command: "mongod --replSet myapp --port 27017"
  #   volumes:
  #     - mongo_data:/data/db
  redis:
    image: redis:6.2.5
    # logging:
    #   driver: none
    ports:
      - 7379:7379
      - 6379:6379
    volumes:
      - ./certificates:/certificates:ro
      - ./redis.conf:/redis.conf:ro
    command:
      - redis-server
      - /redis.conf
