FROM golang:1.17.0-buster

# Install mongoDB client
RUN apt-get update && apt-get install -y gnupg wget
RUN wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.4 main" > /etc/apt/sources.list.d/mongodb-org-4.4.list

RUN apt-get update && apt-get install -y mongodb-org-shell=4.4.8 netcat && rm -rf /var/lib/apt/lists/*

# Build OTR
WORKDIR /oplogtoredis

COPY main.go go.mod go.sum ./
COPY lib ./lib

RUN go build -o /bin/oplogtoredis

ADD scripts/wait-for.sh /wait-for.sh
ADD blackbox-tests/oplogtoredis-entry.sh /oplogtoredis-entry.sh
